### ISSUE TITLE
Remove addresses from public body entries

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/colombia-theme#18]
![address](https://cloud.githubusercontent.com/assets/6806067/20013964/096fe5a0-a2ad-11e6-8fc9-f1d839b9cba7.PNG)

Highlighted in yellow. 

Liz comment: "I think clearing the notes fields that start "<strong>Direccion:</strong>" should do it"3

**Comment by Gemmamysoc** [comment]
Replace it with the authorities' short_name

**Comment by garethrees** [comment]
> Replace it with the authorities' short_name

This happens automatically, e.g. https://www.whatdotheyknow.com/body/dwp

**Comment by lizconlan** [comment]
Done (as in removed notes which were address information). Although most authorities don't have short names
