### ISSUE TITLE
Add Help pages

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/colombia-theme#8]
Partner says she has nearly finished them. Will perhaps send them one by one, or as one big batch

**Comment by garethrees** [comment]
https://docs.google.com/document/d/1Fg5IosV9BSFPozWay1HwIu2ZnStmhdacxkG0jTkhcPU/edit

**Comment by lizconlan** [comment]
Still to do
- [x] Contact Us page (@lizconlan)
- [ ] Small piece of translation
- [ ] Possibly missing the "Your privacy" page (or I've pasted something into the wrong place)
- [ ] Confirmation of intended links
- [ ] Possible replacement example public body on the API page

(email sent evening UK time to try to minimise timezone-related holdups)
